services:
  api:
    depends_on:
      - bdd
    image: marieme81/loona-api
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
      - 8081:3000

  bdd :
    env_file:
      - .env
    image: mysql:latest
    ports:
      - 8082:3306
